version: '3.8'

services:
    php:
        container_name: infrastructure_monitor_php
        env_file:
            - ../.env

    cron:
        container_name: infrastructure_monitor_cron
        env_file:
            - ../.env

    pgsql:
        container_name: infrastructure_monitor_db
        env_file:
            - ../.env
        image: 'postgres:15'
